name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Authenticate with Heroku using API key and set Docker credentials
      - name: Set Docker Credentials
        run: echo $HEROKU_API_KEY | docker login -u _ --password-stdin registry.heroku.com
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          
      # Build and push Docker image to Heroku
      - name: Build and Push Docker Image
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      # Release the Docker container
      - name: Release to Heroku
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
