name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Authenticate with Heroku using API key from secret
      - name: Set Heroku API Key
        run: echo $HEROKU_API_KEY > ~/.netrc
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      # Build and push Docker image to Heroku
      - name: Build and Push Docker Image
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      # Release the Docker containe
      - name: Release to Heroku
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
